name: tsa
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - chardet=3.0.4=py37_1
  - cycler=0.10.0=py37_0
  - decorator=4.3.0=py37_0
  - entrypoints=0.3=py37_0
  - idna=2.8=py37_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - mkl=2019.1=144
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - notebook=5.7.4=py37_0
  - pandas-datareader=0.7.0=py37_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - patsy=0.5.1=py37_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.3.1=py37_0
  - pysocks=1.6.8=py37_0
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.9=py37_0
  - qtconsole=4.4.3=py37_0
  - requests=2.21.0=py37_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - six=1.12.0=py37_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - pip:
    - ephem==3.7.6.0
    - lunardate==0.2.0
    - pycalverter==1.6.1
    - workalendar==3.2.1
